export const CHAPLIN_LAYOUT_SYSTEMS = {
  glassRoundedSoft: {
    id: 'glassRoundedSoft',
    name: 'Glass Rounded Soft',
    cardGeometry: { shape: 'rectangle', radius: '24px', corners: 'uniform' },
    material: { type: 'glass', finish: 'translucent', blur: '20px', fill: 'rgba(255,255,255,0.10)' },
    borders: { type: 'diffuse', width: '1px', color: 'rgba(255,255,255,0.25)', finish: 'soft' },
    shadow: { type: 'physical', value: '0 8px 30px rgba(0,0,0,0.2)' },
    typography: { family: 'Inter, SF Pro Display, sans-serif', weight: 500, tracking: '0.01em' },
    interaction: { hover: 'scale(1.03)', active: 'translateY(1px)', accent: 'increase blur and inner highlight' },
    texture: { type: 'backdrop-blur', detail: 'softened background diffusion' },
    recommendedUse: ['profiles', 'clean dashboards'],
    skinTokens: { shape: 'rounded', radius: '24px', frame: 'solid', material: 'glass', padding: '24px' }
  },
  liquidBubbleUi: {
    id: 'liquidBubbleUi',
    name: 'Liquid Bubble UI',
    cardGeometry: { shape: 'organic', radius: '40px 56px 72px 48px / 60px 44px 70px 52px', corners: 'variable' },
    material: { type: 'gel', finish: 'liquid', blur: '12px', fill: 'radial-gradient(circle at 30% 20%, rgba(255,255,255,0.32), rgba(116,201,255,0.18) 45%, rgba(22,35,74,0.68) 100%)' },
    borders: { type: 'none', width: '0px', color: 'transparent', finish: 'transitioned edge' },
    shadow: { type: 'internal-external-soft', value: 'inset 0 2px 18px rgba(255,255,255,0.2), 0 18px 36px rgba(38,61,120,0.22)' },
    typography: { family: 'Poppins, sans-serif', weight: 500, tracking: '0.01em' },
    interaction: { hover: 'breathing scale 1.02', active: 'gel compression 0.98', accent: 'specular swell' },
    texture: { type: 'radial glossy gradient', detail: 'wet highlight bloom' },
    recommendedUse: ['creative interfaces', 'music UI'],
    skinTokens: { shape: 'cloud', radius: '56px', frame: 'none', material: 'cloud', padding: '26px' }
  },
  chromeReflectivePanels: {
    id: 'chromeReflectivePanels',
    name: 'Chrome Reflective Panels',
    cardGeometry: { shape: 'rectangle', radius: '6px', corners: 'uniform' },
    material: { type: 'chrome', finish: 'reflective metal', blur: '0px', fill: 'linear-gradient(135deg, #fafcff 0%, #aab5c8 18%, #ffffff 38%, #7d8796 62%, #eef4ff 100%)' },
    borders: { type: 'hard', width: '1px', color: '#464c56', finish: 'industrial' },
    shadow: { type: 'specular-reflection', value: '0 10px 24px rgba(0,0,0,0.28)' },
    typography: { family: 'Eurostile, Orbitron, sans-serif', weight: 600, tracking: '0.08em' },
    interaction: { hover: 'dynamic traveling highlight', active: 'press 1px', accent: 'moving specular strip' },
    texture: { type: 'envMap metal', detail: 'cold reflected environment bands' },
    recommendedUse: ['sci-fi industrial UI'],
    skinTokens: { shape: 'sharp', radius: '6px', frame: 'solid', material: 'mirror', padding: '18px' }
  },
  aeroBlurLayers: {
    id: 'aeroBlurLayers',
    name: 'Aero Blur Layers',
    cardGeometry: { shape: 'rectangle', radius: '18px', corners: 'uniform' },
    material: { type: 'layered-glass', finish: 'stacked translucent panes', blur: '30px', fill: 'linear-gradient(180deg, rgba(255,255,255,0.24), rgba(255,255,255,0.08))' },
    borders: { type: 'diffuse', width: '1px', color: 'rgba(255,255,255,0.55)', finish: 'frosted white' },
    shadow: { type: 'elevation-light', value: '0 12px 24px rgba(40,64,102,0.18)' },
    typography: { family: 'Segoe UI, sans-serif', weight: 500, tracking: '0.01em' },
    interaction: { hover: 'layer separation + slight lift', active: 'focus compression', accent: 'dynamic depth shift' },
    texture: { type: 'heavy blur', detail: 'vista-like layered refraction' },
    recommendedUse: ['modernized windows-vista style'],
    skinTokens: { shape: 'rounded', radius: '18px', frame: 'solid', material: 'glass', padding: '22px' }
  },
  neonEdgeMinimal: {
    id: 'neonEdgeMinimal',
    name: 'Neon Edge Minimal',
    cardGeometry: { shape: 'rectangle', radius: '10px', corners: 'uniform' },
    material: { type: 'matte-dark', finish: 'non-reflective', blur: '0px', fill: '#091018' },
    borders: { type: 'neon-line', width: '2px', color: '#00f0ff', finish: 'bright emissive' },
    shadow: { type: 'glow', value: '0 0 26px rgba(0,240,255,0.28)' },
    typography: { family: 'JetBrains Mono, monospace', weight: 600, tracking: '0.04em' },
    interaction: { hover: 'glow intensity x1.4', active: 'hard focus inset', accent: 'edge pulse' },
    texture: { type: 'smooth', detail: 'flat technical matte surface' },
    recommendedUse: ['technical panels'],
    skinTokens: { shape: 'rounded', radius: '10px', frame: 'double', material: 'rubber', padding: '18px' }
  },
  organicFlowCards: {
    id: 'organicFlowCards',
    name: 'Organic Flow Cards',
    cardGeometry: { shape: 'asymmetric-curve', radius: '34px 58px 44px 62px / 48px 42px 60px 36px', corners: 'custom' },
    material: { type: 'organic-skin', finish: 'soft tactile', blur: '0px', fill: 'linear-gradient(155deg, rgba(135,169,112,0.92), rgba(74,102,88,0.88))' },
    borders: { type: 'irregular-soft', width: '1px', color: 'rgba(255,255,255,0.08)', finish: 'bio edge' },
    shadow: { type: 'diffuse', value: '0 18px 28px rgba(17,33,18,0.18)' },
    typography: { family: 'Nunito, sans-serif', weight: 600, tracking: '0.01em' },
    interaction: { hover: 'minor deformation', active: 'pressure dent', accent: 'surface ripple' },
    texture: { type: 'organic noise', detail: 'micro-grain biomorphic surface' },
    recommendedUse: ['generative art interfaces'],
    skinTokens: { shape: 'cloud', radius: '38px', frame: 'solid', material: 'cloud', padding: '26px' }
  },
  floatingTransparentTiles: {
    id: 'floatingTransparentTiles',
    name: 'Floating Transparent Tiles',
    cardGeometry: { shape: 'rectangle', radius: '16px', corners: 'uniform' },
    material: { type: 'clear-glass', finish: 'premium transparent', blur: '16px', fill: 'rgba(255,255,255,0.10)' },
    borders: { type: 'soft-line', width: '1px', color: 'rgba(255,255,255,0.18)', finish: 'thin white' },
    shadow: { type: 'deep-floating', value: '0 24px 60px rgba(0,0,0,0.24)' },
    typography: { family: 'SF Pro Display, sans-serif', weight: 500, tracking: '0.01em' },
    interaction: { hover: 'translateZ feel with 8px lift', active: 'settle to 2px lift', accent: 'subtle parallax' },
    texture: { type: 'light blur', detail: 'air-filled glass tile' },
    recommendedUse: ['premium dashboards'],
    skinTokens: { shape: 'rounded', radius: '16px', frame: 'solid', material: 'glass', padding: '22px' }
  },
  crystalSharpUi: {
    id: 'crystalSharpUi',
    name: 'Crystal Sharp UI',
    cardGeometry: { shape: 'rectangle', radius: '2px', corners: 'hard' },
    material: { type: 'crystal', finish: 'hard transparent', blur: '0px', fill: 'linear-gradient(145deg, rgba(255,255,255,0.2), rgba(128,174,255,0.14))' },
    borders: { type: 'defined', width: '1px', color: 'rgba(208,232,255,0.7)', finish: 'sharp crystalline' },
    shadow: { type: 'minimal', value: '0 4px 10px rgba(0,0,0,0.1)' },
    typography: { family: 'Roboto Condensed, sans-serif', weight: 600, tracking: '0.05em' },
    interaction: { hover: 'point glint', active: 'cut-glass flash', accent: 'angular reflection' },
    texture: { type: 'angular reflection', detail: 'faceted hard-light refraction' },
    recommendedUse: ['data panels'],
    skinTokens: { shape: 'sharp', radius: '2px', frame: 'solid', material: 'mirror', padding: '16px' }
  },
  holographicLayers: {
    id: 'holographicLayers',
    name: 'Holographic Layers',
    cardGeometry: { shape: 'rectangle', radius: '20px', corners: 'uniform' },
    material: { type: 'hologram', finish: 'iridescent layered light', blur: '10px', fill: 'linear-gradient(135deg, rgba(68,231,255,0.16), rgba(198,99,255,0.18), rgba(255,94,198,0.16))' },
    borders: { type: 'iridescent', width: '1px', color: 'rgba(170,255,255,0.6)', finish: 'chromatic' },
    shadow: { type: 'multicolor-glow', value: '0 0 28px rgba(117,226,255,0.18), 0 0 48px rgba(219,107,255,0.14)' },
    typography: { family: 'Exo 2, sans-serif', weight: 600, tracking: '0.03em' },
    interaction: { hover: 'hue shift + card drift', active: 'short prism flash', accent: 'continuous gradient shift' },
    texture: { type: 'gradient shift', detail: 'spectral laminated holographic foil' },
    recommendedUse: ['futuristic UI'],
    skinTokens: { shape: 'rounded', radius: '20px', frame: 'double', material: 'mirror', padding: '24px' }
  },
  frostedGlassHeavy: {
    id: 'frostedGlassHeavy',
    name: 'Frosted Glass Heavy',
    cardGeometry: { shape: 'rectangle', radius: '28px', corners: 'uniform' },
    material: { type: 'frosted-glass', finish: 'heavy matte translucency', blur: '40px', fill: 'rgba(255,255,255,0.16)' },
    borders: { type: 'soft-white', width: '1px', color: 'rgba(255,255,255,0.34)', finish: 'misted' },
    shadow: { type: 'diffuse', value: '0 18px 44px rgba(0,0,0,0.14)' },
    typography: { family: 'Inter, sans-serif', weight: 500, tracking: '0.01em' },
    interaction: { hover: 'opacity increase', active: 'compress blur field', accent: 'noise brightening' },
    texture: { type: 'blur+noise', detail: 'dense frosted grain' },
    recommendedUse: ['overlays'],
    skinTokens: { shape: 'rounded', radius: '28px', frame: 'solid', material: 'glass', padding: '28px' }
  },
  metallicSoftUi: {
    id: 'metallicSoftUi',
    name: 'Metallic Soft UI',
    cardGeometry: { shape: 'rectangle', radius: '12px', corners: 'uniform' },
    material: { type: 'brushed-aluminum', finish: 'soft metallic', blur: '0px', fill: 'linear-gradient(180deg, #cfd5db, #8d949f)' },
    borders: { type: 'bevel-soft', width: '1px', color: 'rgba(255,255,255,0.26)', finish: 'brushed bevel' },
    shadow: { type: 'subtle', value: '0 8px 18px rgba(18,24,31,0.14)' },
    typography: { family: 'Helvetica Neue, Arial, sans-serif', weight: 500, tracking: '0.015em' },
    interaction: { hover: 'linear highlight sweep', active: 'metal press', accent: 'directional sheen' },
    texture: { type: 'brushed metal', detail: 'horizontal machining lines' },
    recommendedUse: ['professional UI'],
    skinTokens: { shape: 'rounded', radius: '12px', frame: 'solid', material: 'metal', padding: '18px' }
  },
  fluidMorphCards: {
    id: 'fluidMorphCards',
    name: 'Fluid Morph Cards',
    cardGeometry: { shape: 'animated-rectangle', radius: '16px → 48px dynamic', corners: 'morphing' },
    material: { type: 'liquid', finish: 'animated fluid membrane', blur: '8px', fill: 'linear-gradient(145deg, rgba(255,196,118,0.24), rgba(110,159,255,0.18))' },
    borders: { type: 'transitional', width: '1px', color: 'rgba(255,255,255,0.12)', finish: 'shape-following' },
    shadow: { type: 'soft', value: '0 16px 30px rgba(32,48,92,0.18)' },
    typography: { family: 'Poppins, sans-serif', weight: 500, tracking: '0.02em' },
    interaction: { hover: 'continuous morph', active: 'shape rebound', accent: 'gradient flow' },
    texture: { type: 'dynamic gradient', detail: 'slow color migration' },
    recommendedUse: ['experimental interfaces'],
    skinTokens: { shape: 'cloud', radius: '32px', frame: 'solid', material: 'cloud', padding: '24px' }
  },
  lightBeamUi: {
    id: 'lightBeamUi',
    name: 'Light Beam UI',
    cardGeometry: { shape: 'rectangle', radius: '14px', corners: 'uniform' },
    material: { type: 'translucent', finish: 'beam-lit layer', blur: '14px', fill: 'linear-gradient(180deg, rgba(255,255,255,0.12), rgba(14,22,34,0.76))' },
    borders: { type: 'light-edge', width: '1px', color: 'rgba(255,255,255,0.22)', finish: 'vertical beam accent' },
    shadow: { type: 'beam-light', value: '0 0 34px rgba(243,252,255,0.14)' },
    typography: { family: 'Montserrat, sans-serif', weight: 600, tracking: '0.03em' },
    interaction: { hover: 'vertical beam sweep', active: 'beam collapse', accent: 'light streak animation' },
    texture: { type: 'light rays', detail: 'vertical luminance banding' },
    recommendedUse: ['hero UI'],
    skinTokens: { shape: 'rounded', radius: '14px', frame: 'solid', material: 'glass', padding: '20px' }
  },
  retroFuturisticPanels: {
    id: 'retroFuturisticPanels',
    name: 'Retro Futuristic Panels',
    cardGeometry: { shape: 'rectangle', radius: '4px', corners: 'hard' },
    material: { type: 'hard-plastic', finish: 'vintage molded shell', blur: '0px', fill: 'linear-gradient(180deg, #5f6671, #343944)' },
    borders: { type: 'double-line', width: '2px', color: '#aab3c3', finish: 'retro shell trim' },
    shadow: { type: 'hard', value: '0 10px 0 rgba(12,16,23,0.28), 0 18px 26px rgba(0,0,0,0.28)' },
    typography: { family: 'MS Sans Serif, VT323, sans-serif', weight: 600, tracking: '0.04em' },
    interaction: { hover: 'minor flicker', active: 'crt push-in', accent: 'scanline flash' },
    texture: { type: 'pixel noise', detail: 'retro display grain' },
    recommendedUse: ['retro UI'],
    skinTokens: { shape: 'sharp', radius: '4px', frame: 'double', material: 'lacquer', padding: '16px' }
  },
  softShadowMinimal: {
    id: 'softShadowMinimal',
    name: 'Soft Shadow Minimal',
    cardGeometry: { shape: 'rectangle', radius: '12px', corners: 'uniform' },
    material: { type: 'matte', finish: 'plain clean', blur: '0px', fill: '#ffffff' },
    borders: { type: 'none', width: '0px', color: 'transparent', finish: 'borderless' },
    shadow: { type: 'soft', value: '0 4px 12px rgba(0,0,0,0.1)' },
    typography: { family: 'Inter, sans-serif', weight: 500, tracking: '0.01em' },
    interaction: { hover: 'slight elevation', active: 'settled shadow', accent: 'micro-contrast bump' },
    texture: { type: 'none', detail: 'clean flat surface' },
    recommendedUse: ['minimal UI'],
    skinTokens: { shape: 'rounded', radius: '12px', frame: 'none', material: 'cloud', padding: '20px' }
  },
  aeroRibbonLayout: {
    id: 'aeroRibbonLayout',
    name: 'Aero Ribbon Layout',
    cardGeometry: { shape: 'curved-ribbon', radius: '26px 26px 12px 12px', corners: 'ribboned' },
    material: { type: 'light-glass', finish: 'curved translucent strip', blur: '16px', fill: 'linear-gradient(90deg, rgba(255,255,255,0.18), rgba(171,208,255,0.16))' },
    borders: { type: 'soft', width: '1px', color: 'rgba(255,255,255,0.32)', finish: 'aero trim' },
    shadow: { type: 'light', value: '0 10px 18px rgba(52,81,126,0.12)' },
    typography: { family: 'Segoe UI, sans-serif', weight: 500, tracking: '0.02em' },
    interaction: { hover: 'ribbon slide', active: 'ribbon lock', accent: 'gradient offset' },
    texture: { type: 'gradient', detail: 'vista ribbon refraction' },
    recommendedUse: ['navigation'],
    skinTokens: { shape: 'oval', radius: '24px', frame: 'solid', material: 'glass', padding: '18px' }
  },
  prismUi: {
    id: 'prismUi',
    name: 'Prism UI',
    cardGeometry: { shape: 'faceted-rectangle', radius: '8px', corners: 'angled facets' },
    material: { type: 'prism', finish: 'refractive crystal', blur: '0px', fill: 'linear-gradient(135deg, rgba(255,0,120,0.16), rgba(0,190,255,0.16), rgba(255,240,0,0.14))' },
    borders: { type: 'angular', width: '1px', color: 'rgba(255,255,255,0.35)', finish: 'facet highlight' },
    shadow: { type: 'refractive', value: '0 16px 36px rgba(93,76,152,0.18)' },
    typography: { family: 'Exo, sans-serif', weight: 600, tracking: '0.04em' },
    interaction: { hover: 'refraction drift', active: 'prism collapse', accent: 'rainbow shear' },
    texture: { type: 'rainbow spectrum', detail: 'spectral refraction bands' },
    recommendedUse: ['visualization'],
    skinTokens: { shape: 'chamfer', radius: '8px', frame: 'double', material: 'mirror', padding: '20px' }
  },
  liquidNeonBlend: {
    id: 'liquidNeonBlend',
    name: 'Liquid Neon Blend',
    cardGeometry: { shape: 'organic', radius: '46px 32px 60px 28px / 32px 52px 28px 60px', corners: 'liquid' },
    material: { type: 'liquid-neon', finish: 'fluid emissive gel', blur: '14px', fill: 'radial-gradient(circle at 35% 20%, rgba(0,255,255,0.35), rgba(255,0,153,0.22) 45%, rgba(15,19,42,0.78) 100%)' },
    borders: { type: 'diffuse', width: '1px', color: 'rgba(0,255,255,0.18)', finish: 'blurred neon edge' },
    shadow: { type: 'glow', value: '0 0 30px rgba(0,255,255,0.18), 0 0 52px rgba(255,0,153,0.12)' },
    typography: { family: 'Orbitron, sans-serif', weight: 700, tracking: '0.05em' },
    interaction: { hover: 'pulse 1.04', active: 'liquid squeeze', accent: 'neon pulsation' },
    texture: { type: 'fluid neon', detail: 'emissive chroma currents' },
    recommendedUse: ['music interfaces'],
    skinTokens: { shape: 'cloud', radius: '34px', frame: 'solid', material: 'cloud', padding: '24px' }
  },
  smoothPlasticUi: {
    id: 'smoothPlasticUi',
    name: 'Smooth Plastic UI',
    cardGeometry: { shape: 'rectangle', radius: '18px', corners: 'uniform' },
    material: { type: 'glossy-plastic', finish: 'polished shell', blur: '0px', fill: 'linear-gradient(180deg, #f4f8ff 0%, #d9e4f8 55%, #c7d2e8 100%)' },
    borders: { type: 'soft', width: '1px', color: 'rgba(255,255,255,0.36)', finish: 'rounded shell trim' },
    shadow: { type: 'light', value: '0 10px 22px rgba(85,112,159,0.16)' },
    typography: { family: 'Arial Rounded MT Bold, Arial Rounded, sans-serif', weight: 600, tracking: '0.01em' },
    interaction: { hover: 'top highlight sweep', active: 'button shell press', accent: 'gloss roll' },
    texture: { type: 'glossy', detail: 'plastic casing sheen' },
    recommendedUse: ['casual interfaces'],
    skinTokens: { shape: 'rounded', radius: '18px', frame: 'solid', material: 'lacquer', padding: '20px' }
  },
  gelUi: {
    id: 'gelUi',
    name: 'Gel UI',
    cardGeometry: { shape: 'bubble', radius: '999px 999px 46px 46px', corners: 'soft gel' },
    material: { type: 'transparent-gel', finish: 'compressible jelly', blur: '12px', fill: 'linear-gradient(180deg, rgba(255,255,255,0.24), rgba(137,197,255,0.18) 45%, rgba(75,108,178,0.48) 100%)' },
    borders: { type: 'diffuse', width: '1px', color: 'rgba(255,255,255,0.16)', finish: 'gel edge' },
    shadow: { type: 'inner', value: 'inset 0 6px 18px rgba(255,255,255,0.18), 0 16px 30px rgba(26,47,94,0.18)' },
    typography: { family: 'Nunito, sans-serif', weight: 600, tracking: '0.015em' },
    interaction: { hover: 'soft wobble', active: 'compression', accent: 'liquid recovery bounce' },
    texture: { type: 'liquid', detail: 'deep translucent gel body' },
    recommendedUse: ['touch-first UI'],
    skinTokens: { shape: 'pill', radius: '999px', frame: 'solid', material: 'cloud', padding: '20px' }
  },
  hyperCleanWhiteAero: {
    id: 'hyperCleanWhiteAero',
    name: 'Hyper Clean White Aero',
    cardGeometry: { shape: 'rectangle', radius: '20px', corners: 'uniform' },
    material: { type: 'pure-white', finish: 'ultra-clean', blur: '0px', fill: '#ffffff' },
    borders: { type: 'none', width: '0px', color: 'transparent', finish: 'seamless' },
    shadow: { type: 'soft', value: '0 16px 40px rgba(15,28,44,0.08)' },
    typography: { family: 'SF Pro Display, sans-serif', weight: 500, tracking: '0.01em' },
    interaction: { hover: 'shadow deepen slightly', active: 'focus compression', accent: 'subtle luminance shift' },
    texture: { type: 'none', detail: 'pristine white surface' },
    recommendedUse: ['apple-like systems'],
    skinTokens: { shape: 'rounded', radius: '20px', frame: 'none', material: 'cloud', padding: '24px' }
  },
  darkGlassContrast: {
    id: 'darkGlassContrast',
    name: 'Dark Glass Contrast',
    cardGeometry: { shape: 'rectangle', radius: '18px', corners: 'uniform' },
    material: { type: 'dark-glass', finish: 'smoked transparency', blur: '24px', fill: 'rgba(11,16,24,0.72)' },
    borders: { type: 'solid', width: '1px', color: 'rgba(153,163,182,0.22)', finish: 'dark polished line' },
    shadow: { type: 'deep', value: '0 24px 48px rgba(0,0,0,0.34)' },
    typography: { family: 'Inter, sans-serif', weight: 500, tracking: '0.01em' },
    interaction: { hover: 'edge glow', active: 'glass pressure darken', accent: 'contrast pulse' },
    texture: { type: 'blurred smoke', detail: 'dark refracted layers' },
    recommendedUse: ['dark mode'],
    skinTokens: { shape: 'rounded', radius: '18px', frame: 'solid', material: 'glass', padding: '22px' }
  },
  floatingCapsules: {
    id: 'floatingCapsules',
    name: 'Floating Capsules',
    cardGeometry: { shape: 'capsule', radius: '999px', corners: 'pill' },
    material: { type: 'glass', finish: 'capsule transparent', blur: '14px', fill: 'linear-gradient(180deg, rgba(255,255,255,0.18), rgba(175,210,255,0.10))' },
    borders: { type: 'none', width: '0px', color: 'transparent', finish: 'airborne shell' },
    shadow: { type: 'floating', value: '0 16px 34px rgba(27,49,91,0.16)' },
    typography: { family: 'Poppins, sans-serif', weight: 600, tracking: '0.02em' },
    interaction: { hover: 'scale 1.04', active: 'scale 0.98', accent: 'capsule float' },
    texture: { type: 'gradient', detail: 'air bubble capsule shading' },
    recommendedUse: ['buttons'],
    skinTokens: { shape: 'pill', radius: '999px', frame: 'none', material: 'glass', padding: '14px 22px' }
  },
  roundedDepthUi: {
    id: 'roundedDepthUi',
    name: 'Rounded Depth UI',
    cardGeometry: { shape: 'rectangle', radius: '22px', corners: 'uniform' },
    material: { type: 'matte', finish: 'layered depth', blur: '0px', fill: 'linear-gradient(180deg, #1a2434, #0f1725)' },
    borders: { type: 'none', width: '0px', color: 'transparent', finish: 'shadow-built' },
    shadow: { type: 'multi-layer', value: '0 2px 6px rgba(0,0,0,0.12), 0 10px 26px rgba(0,0,0,0.16), 0 24px 48px rgba(0,0,0,0.18)' },
    typography: { family: 'Inter, sans-serif', weight: 500, tracking: '0.01em' },
    interaction: { hover: 'depth increase', active: 'inner settle', accent: 'stacked shadow shift' },
    texture: { type: 'none', detail: 'solid clean depth planes' },
    recommendedUse: ['dashboards'],
    skinTokens: { shape: 'rounded', radius: '22px', frame: 'none', material: 'rubber', padding: '24px' }
  },
  gradientBorderUi: {
    id: 'gradientBorderUi',
    name: 'Gradient Border UI',
    cardGeometry: { shape: 'rectangle', radius: '16px', corners: 'uniform' },
    material: { type: 'neutral', finish: 'quiet center panel', blur: '0px', fill: 'linear-gradient(180deg, rgba(15,19,30,0.92), rgba(10,12,22,0.96))' },
    borders: { type: 'animated-gradient', width: '2px', color: 'linear-gradient(90deg, #4de2ff, #ff6bc1, #ffd86b, #4de2ff)', finish: 'traveling color frame' },
    shadow: { type: 'light', value: '0 12px 26px rgba(0,0,0,0.16)' },
    typography: { family: 'Montserrat, sans-serif', weight: 600, tracking: '0.03em' },
    interaction: { hover: 'border animate faster', active: 'pause at active segment', accent: 'chromatic frame rotation' },
    texture: { type: 'gradient', detail: 'animated perimeter only' },
    recommendedUse: ['highlight areas'],
    skinTokens: { shape: 'rounded', radius: '16px', frame: 'double', material: 'rubber', padding: '20px' }
  },
  translucentStackUi: {
    id: 'translucentStackUi',
    name: 'Translucent Stack UI',
    cardGeometry: { shape: 'rectangle', radius: '20px', corners: 'uniform' },
    material: { type: 'stacked-glass', finish: 'layered translucency', blur: '24px', fill: 'rgba(255,255,255,0.12)' },
    borders: { type: 'soft', width: '1px', color: 'rgba(255,255,255,0.2)', finish: 'stack outline' },
    shadow: { type: 'stacking', value: '0 8px 18px rgba(0,0,0,0.08), 0 18px 40px rgba(0,0,0,0.12)' },
    typography: { family: 'SF Pro Display, sans-serif', weight: 500, tracking: '0.01em' },
    interaction: { hover: 'parallax stack separation', active: 'stack compress', accent: 'depth slide' },
    texture: { type: 'blur', detail: 'multi-pane transparent stack' },
    recommendedUse: ['multitasking surfaces'],
    skinTokens: { shape: 'rounded', radius: '20px', frame: 'solid', material: 'glass', padding: '24px' }
  },
  dynamicGlowUi: {
    id: 'dynamicGlowUi',
    name: 'Dynamic Glow UI',
    cardGeometry: { shape: 'rectangle', radius: '14px', corners: 'uniform' },
    material: { type: 'dark', finish: 'reactive neon shell', blur: '0px', fill: '#070b14' },
    borders: { type: 'reactive-glow', width: '2px', color: '#43f7ff', finish: 'audio-responsive edge' },
    shadow: { type: 'intense', value: '0 0 18px rgba(67,247,255,0.22), 0 0 44px rgba(67,247,255,0.16)' },
    typography: { family: 'Orbitron, sans-serif', weight: 700, tracking: '0.06em' },
    interaction: { hover: 'glow rise', active: 'glow contract', accent: 'audio reactive bloom' },
    texture: { type: 'neon', detail: 'light-emitting panel traces' },
    recommendedUse: ['music interfaces'],
    skinTokens: { shape: 'rounded', radius: '14px', frame: 'double', material: 'rubber', padding: '18px' }
  },
  softTechUi: {
    id: 'softTechUi',
    name: 'Soft Tech UI',
    cardGeometry: { shape: 'rectangle', radius: '10px', corners: 'uniform' },
    material: { type: 'matte', finish: 'clean tech plastic', blur: '0px', fill: '#121823' },
    borders: { type: 'fine', width: '1px', color: 'rgba(180,194,216,0.12)', finish: 'quiet technical line' },
    shadow: { type: 'light', value: '0 8px 16px rgba(0,0,0,0.12)' },
    typography: { family: 'Roboto, sans-serif', weight: 500, tracking: '0.01em' },
    interaction: { hover: 'simple lift', active: 'focus inset', accent: 'slight tint shift' },
    texture: { type: 'none', detail: 'clean productivity shell' },
    recommendedUse: ['productive tools'],
    skinTokens: { shape: 'rounded', radius: '10px', frame: 'solid', material: 'rubber', padding: '18px' }
  },
  minimalBlurUi: {
    id: 'minimalBlurUi',
    name: 'Minimal Blur UI',
    cardGeometry: { shape: 'rectangle', radius: '12px', corners: 'uniform' },
    material: { type: 'light-glass', finish: 'subtle blur', blur: '10px', fill: 'rgba(255,255,255,0.08)' },
    borders: { type: 'none', width: '0px', color: 'transparent', finish: 'edge-free' },
    shadow: { type: 'minimal', value: '0 8px 18px rgba(0,0,0,0.08)' },
    typography: { family: 'Inter, sans-serif', weight: 500, tracking: '0.01em' },
    interaction: { hover: 'fade-in clarity', active: 'soft settle', accent: 'backdrop focus' },
    texture: { type: 'blur-10', detail: 'gentle optical diffusion' },
    recommendedUse: ['overlays'],
    skinTokens: { shape: 'rounded', radius: '12px', frame: 'none', material: 'glass', padding: '18px' }
  },
  crystalLayers: {
    id: 'crystalLayers',
    name: 'Crystal Layers',
    cardGeometry: { shape: 'layered-rectangle', radius: '4px', corners: 'sharp' },
    material: { type: 'crystal', finish: 'stacked transparent plates', blur: '0px', fill: 'linear-gradient(180deg, rgba(225,244,255,0.18), rgba(66,100,164,0.12))' },
    borders: { type: 'sharp', width: '1px', color: 'rgba(219,238,255,0.56)', finish: 'hard crystal edge' },
    shadow: { type: 'light', value: '0 10px 20px rgba(0,0,0,0.1)' },
    typography: { family: 'Exo, sans-serif', weight: 600, tracking: '0.03em' },
    interaction: { hover: 'layer shift', active: 'layer snap', accent: 'refraction split' },
    texture: { type: 'refractive', detail: 'crystal plate parallax' },
    recommendedUse: ['data interfaces'],
    skinTokens: { shape: 'sharp', radius: '4px', frame: 'double', material: 'mirror', padding: '18px' }
  },
  floatingGlassStrips: {
    id: 'floatingGlassStrips',
    name: 'Floating Glass Strips',
    cardGeometry: { shape: 'horizontal-strip', radius: '14px', corners: 'uniform' },
    material: { type: 'glass', finish: 'clear strip layers', blur: '18px', fill: 'rgba(255,255,255,0.11)' },
    borders: { type: 'soft', width: '1px', color: 'rgba(255,255,255,0.18)', finish: 'strip highlight' },
    shadow: { type: 'light', value: '0 12px 20px rgba(0,0,0,0.10)' },
    typography: { family: 'Segoe UI, sans-serif', weight: 500, tracking: '0.02em' },
    interaction: { hover: 'horizontal slide', active: 'align snap', accent: 'list ribbon motion' },
    texture: { type: 'blur', detail: 'airy glass list rows' },
    recommendedUse: ['lists'],
    skinTokens: { shape: 'oval', radius: '14px', frame: 'solid', material: 'glass', padding: '14px 18px' }
  },
  neonSoftUi: {
    id: 'neonSoftUi',
    name: 'Neon Soft UI',
    cardGeometry: { shape: 'rectangle', radius: '18px', corners: 'uniform' },
    material: { type: 'dark', finish: 'soft neon cavity', blur: '0px', fill: '#0b0f19' },
    borders: { type: 'soft-glow', width: '1px', color: 'rgba(0,255,224,0.55)', finish: 'diffuse neon line' },
    shadow: { type: 'diffuse', value: '0 0 30px rgba(0,255,224,0.12)' },
    typography: { family: 'Orbitron, sans-serif', weight: 600, tracking: '0.05em' },
    interaction: { hover: 'fade glow in', active: 'glow contract', accent: 'neon halo' },
    texture: { type: 'neon', detail: 'soft edge light bleed' },
    recommendedUse: ['night UI'],
    skinTokens: { shape: 'rounded', radius: '18px', frame: 'solid', material: 'rubber', padding: '20px' }
  },
  smoothEdgeUi: {
    id: 'smoothEdgeUi',
    name: 'Smooth Edge UI',
    cardGeometry: { shape: 'rectangle', radius: '12px', corners: 'uniform' },
    material: { type: 'matte', finish: 'neutral soft', blur: '0px', fill: '#141b26' },
    borders: { type: 'soft', width: '1px', color: 'rgba(255,255,255,0.08)', finish: 'low-contrast line' },
    shadow: { type: 'light', value: '0 10px 18px rgba(0,0,0,0.1)' },
    typography: { family: 'Inter, sans-serif', weight: 500, tracking: '0.01em' },
    interaction: { hover: 'subtle brightness', active: 'tiny inset', accent: 'micro lift' },
    texture: { type: 'none', detail: 'universal smooth utility surface' },
    recommendedUse: ['general-purpose UI'],
    skinTokens: { shape: 'rounded', radius: '12px', frame: 'solid', material: 'rubber', padding: '18px' }
  },
  blurStackSystem: {
    id: 'blurStackSystem',
    name: 'Blur Stack System',
    cardGeometry: { shape: 'stacked-layers', radius: '20px', corners: 'uniform' },
    material: { type: 'glass-stack', finish: 'depth blurred layers', blur: '24px', fill: 'rgba(255,255,255,0.12)' },
    borders: { type: 'soft', width: '1px', color: 'rgba(255,255,255,0.16)', finish: 'layer separation line' },
    shadow: { type: 'stacking', value: '0 6px 12px rgba(0,0,0,0.08), 0 20px 44px rgba(0,0,0,0.12)' },
    typography: { family: 'SF Pro Display, sans-serif', weight: 500, tracking: '0.01em' },
    interaction: { hover: 'depth amplify', active: 'layer snap', accent: 'stack depth motion' },
    texture: { type: 'blur', detail: 'layered multitask glass planes' },
    recommendedUse: ['multitasking systems'],
    skinTokens: { shape: 'rounded', radius: '20px', frame: 'solid', material: 'glass', padding: '24px' }
  },
  ultraLightUi: {
    id: 'ultraLightUi',
    name: 'Ultra Light UI',
    cardGeometry: { shape: 'rectangle', radius: '14px', corners: 'uniform' },
    material: { type: 'light-white', finish: 'feather minimal', blur: '0px', fill: '#fcfdff' },
    borders: { type: 'none', width: '0px', color: 'transparent', finish: 'silent' },
    shadow: { type: 'minimal', value: '0 6px 18px rgba(12,22,38,0.05)' },
    typography: { family: 'Inter, sans-serif', weight: 500, tracking: '0.01em' },
    interaction: { hover: 'fade elevation', active: 'stillness', accent: 'slight warmth shift' },
    texture: { type: 'none', detail: 'reading-first clean sheet' },
    recommendedUse: ['reading interfaces'],
    skinTokens: { shape: 'rounded', radius: '14px', frame: 'none', material: 'cloud', padding: '22px' }
  },
  aeroDepthCards: {
    id: 'aeroDepthCards',
    name: 'Aero Depth Cards',
    cardGeometry: { shape: 'rectangle', radius: '20px', corners: 'uniform' },
    material: { type: 'glass', finish: 'deep aero plate', blur: '26px', fill: 'rgba(255,255,255,0.12)' },
    borders: { type: 'soft', width: '1px', color: 'rgba(255,255,255,0.22)', finish: 'aero highlight' },
    shadow: { type: 'deep', value: '0 20px 48px rgba(35,60,104,0.18)' },
    typography: { family: 'Segoe UI, sans-serif', weight: 500, tracking: '0.015em' },
    interaction: { hover: 'elevation', active: 'soft settle', accent: 'vista depth bloom' },
    texture: { type: 'blur', detail: 'deep aero pane' },
    recommendedUse: ['panels'],
    skinTokens: { shape: 'rounded', radius: '20px', frame: 'solid', material: 'glass', padding: '24px' }
  },
  softChromeUi: {
    id: 'softChromeUi',
    name: 'Soft Chrome UI',
    cardGeometry: { shape: 'rectangle', radius: '10px', corners: 'uniform' },
    material: { type: 'soft-metal', finish: 'polished brushed chrome', blur: '0px', fill: 'linear-gradient(180deg, #eef2f7, #adb5c0)' },
    borders: { type: 'soft', width: '1px', color: 'rgba(255,255,255,0.28)', finish: 'smoothed chrome rim' },
    shadow: { type: 'light', value: '0 8px 18px rgba(0,0,0,0.12)' },
    typography: { family: 'Helvetica, Helvetica Neue, Arial, sans-serif', weight: 500, tracking: '0.015em' },
    interaction: { hover: 'highlight shift', active: 'firm press', accent: 'chrome gleam' },
    texture: { type: 'brushed', detail: 'fine soft metal grain' },
    recommendedUse: ['tool UIs'],
    skinTokens: { shape: 'rounded', radius: '10px', frame: 'solid', material: 'metal', padding: '18px' }
  },
  elasticUi: {
    id: 'elasticUi',
    name: 'Elastic UI',
    cardGeometry: { shape: 'rectangle', radius: '18px', corners: 'uniform elastic' },
    material: { type: 'gel', finish: 'stretchy elastic skin', blur: '8px', fill: 'linear-gradient(180deg, rgba(255,255,255,0.22), rgba(155,188,255,0.16))' },
    borders: { type: 'soft', width: '1px', color: 'rgba(255,255,255,0.14)', finish: 'stretch edge' },
    shadow: { type: 'light', value: '0 10px 22px rgba(52,77,135,0.14)' },
    typography: { family: 'Nunito, sans-serif', weight: 600, tracking: '0.01em' },
    interaction: { hover: 'bounce 1.03', active: 'elastic snap 0.96', accent: 'rubber rebound' },
    texture: { type: 'soft', detail: 'mobile-friendly elastic surface' },
    recommendedUse: ['mobile interfaces'],
    skinTokens: { shape: 'rounded', radius: '18px', frame: 'solid', material: 'cloud', padding: '20px' }
  },
  airyPanels: {
    id: 'airyPanels',
    name: 'Airy Panels',
    cardGeometry: { shape: 'rectangle', radius: '24px', corners: 'uniform' },
    material: { type: 'airy-glass', finish: 'light breathable translucency', blur: '18px', fill: 'rgba(255,255,255,0.08)' },
    borders: { type: 'none', width: '0px', color: 'transparent', finish: 'floating clean edge' },
    shadow: { type: 'light', value: '0 14px 28px rgba(17,31,55,0.08)' },
    typography: { family: 'Inter, sans-serif', weight: 500, tracking: '0.01em' },
    interaction: { hover: 'fade upward', active: 'float settle', accent: 'air glow' },
    texture: { type: 'blur', detail: 'high-air low-weight paneling' },
    recommendedUse: ['minimal surfaces'],
    skinTokens: { shape: 'rounded', radius: '24px', frame: 'none', material: 'glass', padding: '24px' }
  },
  hybridAeroCyber: {
    id: 'hybridAeroCyber',
    name: 'Hybrid Aero Cyber',
    cardGeometry: { shape: 'rectangle', radius: '16px', corners: 'uniform' },
    material: { type: 'glass-neon', finish: 'aero shell with cyber glow', blur: '22px', fill: 'linear-gradient(135deg, rgba(255,255,255,0.14), rgba(0,240,255,0.10), rgba(255,0,146,0.10))' },
    borders: { type: 'glow-line', width: '1px', color: 'rgba(0,240,255,0.55)', finish: 'neon + linear trim' },
    shadow: { type: 'intense', value: '0 0 20px rgba(0,240,255,0.18), 0 22px 42px rgba(0,0,0,0.22)' },
    typography: { family: 'Orbitron, Inter, sans-serif', weight: 600, tracking: '0.04em' },
    interaction: { hover: 'audio-reactive glow + lift', active: 'edge pulse contract', accent: 'hybrid bloom' },
    texture: { type: 'gradient+glow', detail: 'aero translucency fused with cyber emission' },
    recommendedUse: ['advanced music systems'],
    skinTokens: { shape: 'rounded', radius: '16px', frame: 'double', material: 'glass', padding: '22px' }
  }
};

export const CHAPLIN_LAYOUT_SYSTEM_LIST = Object.values(CHAPLIN_LAYOUT_SYSTEMS);