"""
Converts the measured wave geometry (body upper/lower boundary from
trace_wave_thickness.py, highlight cores from trace_wave_contour.py) into
smooth SVG cubic-Bezier path strings, via Catmull-Rom spline fitting through
a controlled, downsampled point set (not the raw pixel contour).

Point-count discipline: prefer ~40-90 real, curvature-representative points
over thousands of raw pixels — downsampling is arc-length-uniform, not
naive index-stride, so it doesn't lose sharp features (the curls).
"""
import json
import numpy as np

GEOM_DIR = r"C:\Users\MaxJokerExtrem\Desktop\Chaplin\tools\player-reconstruction\geometry"
OUT_JS = r"C:\Users\MaxJokerExtrem\Desktop\Chaplin\frontend\web\src\components\ProfilePlayer\reconstructed\aquaFlow\waveGeometry.js"


def catmull_rom_to_bezier(points, closed=False):
    """points: list of (x,y). Returns list of cubic bezier segments
    [(p0,c1,c2,p1), ...] using the standard Catmull-Rom -> Bezier control
    point formula (uniform, tension 0)."""
    pts = points[:]
    n = len(pts)
    if n < 3:
        return []
    segs = []
    rng = range(n) if closed else range(n - 1)
    for i in rng:
        p0 = pts[(i - 1) % n] if closed or i > 0 else pts[i]
        p1 = pts[i % n]
        p2 = pts[(i + 1) % n]
        p3 = pts[(i + 2) % n] if closed or i + 2 < n else p2
        c1 = (p1[0] + (p2[0] - p0[0]) / 6.0, p1[1] + (p2[1] - p0[1]) / 6.0)
        c2 = (p2[0] - (p3[0] - p1[0]) / 6.0, p2[1] - (p3[1] - p1[1]) / 6.0)
        segs.append((p1, c1, c2, p2))
    return segs


def segs_to_path_d(segs, start_point):
    d = f"M {start_point[0]:.1f} {start_point[1]:.1f} "
    for (_p1, c1, c2, p2) in segs:
        d += f"C {c1[0]:.1f} {c1[1]:.1f} {c2[0]:.1f} {c2[1]:.1f} {p2[0]:.1f} {p2[1]:.1f} "
    return d.strip()


def uniform_arclength_downsample(xs, ys, target_n):
    pts = np.array(list(zip(xs, ys)), dtype=np.float64)
    seg_lens = np.sqrt(((pts[1:] - pts[:-1]) ** 2).sum(axis=1))
    cum = np.concatenate([[0], np.cumsum(seg_lens)])
    total = cum[-1]
    sample_at = np.linspace(0, total, target_n)
    out = []
    j = 0
    for s in sample_at:
        while j < len(cum) - 2 and cum[j + 1] < s:
            j += 1
        seg_len = cum[j + 1] - cum[j]
        t = 0.0 if seg_len == 0 else (s - cum[j]) / seg_len
        x = pts[j][0] + t * (pts[j + 1][0] - pts[j][0])
        y = pts[j][1] + t * (pts[j + 1][1] - pts[j][1])
        out.append((round(x, 1), round(y, 1)))
    return out


def build_body_path():
    with open(f"{GEOM_DIR}\\wave_thickness.json") as f:
        d = json.load(f)
    xs, upper, lower = d["xs"], d["upper"], d["lower"]

    upper_pts = uniform_arclength_downsample(xs, upper, 70)
    lower_pts = uniform_arclength_downsample(xs, lower, 70)
    ring = upper_pts + list(reversed(lower_pts))

    segs = catmull_rom_to_bezier(ring, closed=True)
    path_d = segs_to_path_d(segs, ring[0]) + " Z"
    return path_d, len(ring)


def build_highlight_paths():
    with open(f"{GEOM_DIR}\\wave_contour.json") as f:
        pieces = json.load(f)
    paths = []
    for piece in pieces:
        pts = [(p[0], p[1]) for p in piece["points"]]
        if len(pts) < 3:
            continue
        target = min(len(pts), 55)
        xs = [p[0] for p in pts]
        ys = [p[1] for p in pts]
        pts_ds = uniform_arclength_downsample(xs, ys, target)
        segs = catmull_rom_to_bezier(pts_ds, closed=True)
        path_d = segs_to_path_d(segs, pts_ds[0]) + " Z"
        paths.append({"path": path_d, "area": piece["area"], "points": len(pts_ds)})
    paths.sort(key=lambda p: -p["area"])
    return paths


def main():
    body_path, body_pts = build_body_path()
    highlights = build_highlight_paths()

    js = "// AUTO-GENERATED by tools/player-reconstruction/scripts/fit_wave_paths.py\n"
    js += "// Real measured geometry from reference.png (contour extraction + boundary\n"
    js += "// walk + Catmull-Rom->Bezier fit). Do not hand-edit; re-run the script.\n\n"
    js += f"export const AQUA_WAVE_BODY_PATH = \"{body_path}\";\n\n"
    js += "export const AQUA_WAVE_HIGHLIGHT_PATHS = [\n"
    for h in highlights:
        js += f"  \"{h['path']}\",\n"
    js += "];\n"

    with open(OUT_JS, "w", encoding="utf-8") as f:
        f.write(js)

    print(f"body path: {body_pts} ring points -> {len(body_path)} chars")
    for i, h in enumerate(highlights):
        print(f"highlight {i}: area={h['area']:.0f} points={h['points']}")
    print(f"written to {OUT_JS}")


if __name__ == "__main__":
    main()
